language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
deploy:
- provider: cargo
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux"
    branch: master
  token:
    secure: x1gIDW7GdZyGpbRX6WFafJwTAdhxXTesTT+QJrPagrGEBX4sj8Lt3SOjS6TFTEDjjBklUFK7tF1OwRcDWMaT335KMnY+p1glf6VhWm0CsByjhzeBwKYu87u0DIBB42zVoIIPW+PjLr7sej/HkbfJbOsZ6F/66zSR65zfwyLU28eoITPJfy3YAkBedqDBirOYiOwDopNRVoFCgZzYmkwiQBopVxmlznhcQteuMZUPH7KVLn+IM7kIIvsgZTAEsAxvjs0IwR/pqtgiEn09Ah0Hw5VW/9xl46NxobNyITwrB5HFKc9SXHFbs08ZQXhUZ3jwxoRIc1XHHGhHguqhXlvb3bzYmOcvpormcDDCInAPFFJWGWJKE9sHPUx650KUZqN5InSuRwZ+fV1UoJIeFLzoLUgQj/f9SRA12HOhnDekbi2AzF9oAQ2xxsbD1/8mzaeyXdiInMit1ACSvfikzmy34baZZsVjuYPqIe1xxizdLYbBEe0L7MIVohMbI4kR3q6lRqacJF51aCwVM3XXPAndeMfUrOmYMzYZFxN90y9852/WuEfN7TjYlGxiXv7rVfsg0mdwNNe+cD8sKsicg8w2AsdQ4IFWcn7rSEyFBeastuH8VSVPJYoNOXv3KXCndjHymCrOPsJWQAf5mW7+jTd7j0aD0W3SuFUqLrfpqrUUF+4=
- provider: releases
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
    branch: master
  file:
  - target/release/youtube-subscriptions-*
  api_key:
    secure: JcSZ+ewhIhbhvN369kCmcXq0aA5t/FGyzv5tonukxKVufS7iRC9nFHsuQhj77NV99wOcqfdzfFbZhpC7KFZs9B1WjYyheH0/FGsI07uSCGv1Zs7rATUORIXYqSA/JqWLtW4vdUtLMQIOQvjj+5c02ZqkqBCffE8Qs0xiMzdwwE9gOHnT2d/YCBAnbR71YU7Ew9R8JKQD9XD8cHPMMqglxhxX+JvOwhrg+gwbV9qYJksUCwlRv4UV+eNinNi6z/KFS3IpAMmsshSXgroftMZANOzAA3OQYntk2IRoYqg6enJ/jhtZdQ84tZY6Lv53LA0nWIcrfzYvjo6f0+CzAHaGDbM8qjYQ/1wMZDDEfYKhHuJMTsSHVTRBSEgey4FfcxnXI7A9cWd4V2+KlDOj5F83qdZ93mbRU8SmuwpZe+WDz8oz61ECnNJ+m/azggEGyS1BXLKN1cNVFf8+Jc3Wd5UF9kL5Ch4fr4gw8QphpnzUQ/ak0OjOGHu7t/GxPba8JYIG+O+gbaWiFMZD8IWcK0yqtFHPc4Q6PJB/ydDHNtRcVtQYiTQXa5mfU/8kK4i4BiBbKAvlkfQaMEqmo8mgrLJV1zTvoFa0Pqk4G1wJEgSgFcMuesseKVTqXaCjOrXmPfNUT1OKt6PhnPJr3NAyFSbCt3YMgs/+ZMANPGNZROw5nco=
