---
language: rust
script:
  - ./cross-build-raspberry.sh travis
  - cargo build --release
  - mv target/release/youtube-subscriptions target/release/youtube-subscriptions-$TRAVIS_OS_NAME
services:
  - docker
rust:
- stable
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
- windows
dist:  bionic
before_install:
  - if which apt-get ; then sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev; fi
deploy:
#- provider: cargo
#  skip_cleanup: true
#  on:
#    tags: true
#    condition: "$TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux"
#    branch: master
#  token:
#    secure: XnpPfGnaAkfBNcWGF2jC4bOy2R8HR/10ZK0zEyY3PH5a1Fc6v5Q33G5nUSJYIpm5Qme0IgFYfijBErV/gmJTirVckOLbxCIQQqmVtQDKT9qaZhO8/nPKyYF8S+rIFTuAPmuHAQcoJAYRhNjj3SJKOxB/rSLRHIArg0ArHU/ZbcMIg5cOOBiOFlHxVI0LK8H5phLeI8WbVbr0Wz0+SbOlto8Bc+ltR87qtSk2o3b6cr8n7UCdIPpNXaSQjf73c8Gkm+aJn4R7tardEr/Vsk9C0PW0YL1IbbL9SHPFsXtpPI1IKtroMIFwEicuM4PRA1wQ9W0JFB0dQsXJ1dRxBCncC31xCcxIJRgQDKeK/aHelierJWYr78JLlvh8HLv2P2+dspO53mRPiXECXnQFCMBnx5Btj6HV5LiYKGBOj4opT0m+nSnUuiJNHduCJScsALe72CbVNTqOT2WW3Br4Mb58scbiQDkpmpy19NyeB7azNUpzjIUJ4HpZRTuYUd+4ThZeFDjWGGVKedOWQX2N0rp/Mev1D9FZ6dtljXvBG57SVjFMm/Y++6EWLqF7KfqKGR/oUQoV2NHE3PALjagX0CbLKrBZNebOKUfmhFsKT2fP6vALszYTg4f88aRsH9F+DXzPqsc8s1ifox1hFQ4qRvOOUU2Bd4wo9+kwI9HPVYkBFKo=
- provider: releases
  skip_cleanup: true
  on:
    tags: true
    branch: master
  file:
    - target/release/youtube-subscriptions-$TRAVIS_OS_NAME
    - target/release/youtube-subscriptions-$TRAVIS_OS_NAME-arm 
  api_key:
    secure: x1gIDW7GdZyGpbRX6WFafJwTAdhxXTesTT+QJrPagrGEBX4sj8Lt3SOjS6TFTEDjjBklUFK7tF1OwRcDWMaT335KMnY+p1glf6VhWm0CsByjhzeBwKYu87u0DIBB42zVoIIPW+PjLr7sej/HkbfJbOsZ6F/66zSR65zfwyLU28eoITPJfy3YAkBedqDBirOYiOwDopNRVoFCgZzYmkwiQBopVxmlznhcQteuMZUPH7KVLn+IM7kIIvsgZTAEsAxvjs0IwR/pqtgiEn09Ah0Hw5VW/9xl46NxobNyITwrB5HFKc9SXHFbs08ZQXhUZ3jwxoRIc1XHHGhHguqhXlvb3bzYmOcvpormcDDCInAPFFJWGWJKE9sHPUx650KUZqN5InSuRwZ+fV1UoJIeFLzoLUgQj/f9SRA12HOhnDekbi2AzF9oAQ2xxsbD1/8mzaeyXdiInMit1ACSvfikzmy34baZZsVjuYPqIe1xxizdLYbBEe0L7MIVohMbI4kR3q6lRqacJF51aCwVM3XXPAndeMfUrOmYMzYZFxN90y9852/WuEfN7TjYlGxiXv7rVfsg0mdwNNe+cD8sKsicg8w2AsdQ4IFWcn7rSEyFBeastuH8VSVPJYoNOXv3KXCndjHymCrOPsJWQAf5mW7+jTd7j0aD0W3SuFUqLrfpqrUUF+4=
