[package]
name = "youtube-subscriptions"
version = "0.1.0"
authors = ["yazgoo <yazgoo@gmail.com>"]
edition = "2018"

[dependencies]
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
dirs = "2.0.1"
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
terminal_size = "0.1.8"
crossterm_input = "0.3"
