[package]
name = "youtube-subscriptions"
version = "0.1.0"
authors = ["yazgoo <yazgoo@gmail.com>"]
edition = "2018"
license = "MIT"
description = "terminal UI for viewing youtube subscriptions"
readme = "README.md"
homepage = "https://github.com/yazgoo/youtube-subscriptions"
repository = "https://github.com/yazgoo/youtube-subscriptions"
keywords = ["cli", "youtube", "terminal"]
categories = ["command-line-utilities"]

[dependencies]
sxd-xpath = { version = "0.4.2", default-features = false }
sxd-document = { version = "0.3.2", default-features = false }
dirs = { version = "2.0.1", default-features = false }
reqwest = { version = "0.9.18", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
terminal_size = { version = "0.1.8", default-features = false }
crossterm_input = { version = "0.3", default-features = false }
crossterm = { version = "0.9" }
par-map = { version = "0.1.4", default-features=false }
webbrowser = { version = "0.5", default-features=false }
clipboard = { version = "0.5", default-features=false }
